In [ ]:
import torch
from torch import nn

In [ ]:
embedding_sum = nn.EmbeddingBag(10, 3, mode='sum')
# embedding_sum = nn.EmbeddingBag(5, 3, mode='sum')
embedding_sum.weight

Parameter containing:
tensor([[-3.6467e-01, -8.1340e-01, -1.5706e-01],
        [-8.7280e-01, -3.1360e-01, -2.8003e-01],
        [ 1.2358e+00,  1.1763e-01, -1.2437e-02],
        [ 3.8914e-02, -1.3369e-01, -1.6582e-01],
        [-1.7532e+00, -9.7848e-01,  5.5114e-02],
        [ 4.0866e-01,  4.6727e-01,  7.0462e-01],
        [ 6.8699e-04,  8.5198e-03,  1.0356e+00],
        [-2.0916e+00, -1.0700e+00,  4.0173e-01],
        [-1.2464e-01, -1.6250e+00, -1.0792e+00],
        [-1.3369e+00,  4.8772e-01, -6.4277e-01]], requires_grad=True)

In [ ]:
input = torch.LongTensor([1,2,4,5,4,3,2,9])
# input = torch.LongTensor([1,2,4,5,4,3,2])
input[3]

tensor(5)

In [ ]:
# offsets = torch.LongTensor([0,4])
offsets = torch.LongTensor([0,2,4])
offsets

tensor([0, 2, 4])

In [ ]:
embedding_sum(input, offsets)

tensor([[ 0.3630, -0.1960, -0.2925],
        [-1.3446, -0.5112,  0.7597],
        [-1.8154, -0.5068, -0.7659]], grad_fn=<EmbeddingBagBackward>)

In [ ]:
embedding_sum.weight

Parameter containing:
tensor([[-3.6467e-01, -8.1340e-01, -1.5706e-01],
        [-8.7280e-01, -3.1360e-01, -2.8003e-01],
        [ 1.2358e+00,  1.1763e-01, -1.2437e-02],
        [ 3.8914e-02, -1.3369e-01, -1.6582e-01],
        [-1.7532e+00, -9.7848e-01,  5.5114e-02],
        [ 4.0866e-01,  4.6727e-01,  7.0462e-01],
        [ 6.8699e-04,  8.5198e-03,  1.0356e+00],
        [-2.0916e+00, -1.0700e+00,  4.0173e-01],
        [-1.2464e-01, -1.6250e+00, -1.0792e+00],
        [-1.3369e+00,  4.8772e-01, -6.4277e-01]], requires_grad=True)

In [ ]:
feature_1 = [0,3,4]
feature_