In [79]:
import torch
from torch import nn
import random

In [2]:
embedding_sum = nn.EmbeddingBag(10, 3, mode='sum')
# embedding_sum = nn.EmbeddingBag(5, 3, mode='sum')
embedding_sum.weight

Parameter containing:
tensor([[-0.6892,  0.3329, -0.0888],
        [ 1.5789, -0.4462,  0.2201],
        [ 0.6228, -0.0206,  0.1260],
        [ 0.6314,  0.5015,  0.1724],
        [-0.1079, -0.0558, -1.1736],
        [-1.4469, -0.2794, -2.9468],
        [-0.7668,  0.5491, -0.3083],
        [-1.2309, -1.3998,  0.3947],
        [-0.5466, -0.3768, -0.6833],
        [ 0.3448,  1.6080, -1.1067]], requires_grad=True)

In [3]:
input = torch.LongTensor([1,2,4,5,4,3,2,9])
# input = torch.LongTensor([1,2,4,5,4,3,2])
input[3]

tensor(5)

In [4]:
# offsets = torch.LongTensor([0,4])
offsets = torch.LongTensor([0,2,4])
offsets

tensor([0, 2, 4])

In [10]:
embedding_sum(input, offsets)

tensor([[ 2.2017, -0.4668,  0.3461],
        [-1.5548, -0.3353, -4.1204],
        [ 1.4913,  2.0331, -1.9819]], grad_fn=<EmbeddingBagBackward>)

In [6]:
embedding_sum.weight

Parameter containing:
tensor([[-0.6892,  0.3329, -0.0888],
        [ 1.5789, -0.4462,  0.2201],
        [ 0.6228, -0.0206,  0.1260],
        [ 0.6314,  0.5015,  0.1724],
        [-0.1079, -0.0558, -1.1736],
        [-1.4469, -0.2794, -2.9468],
        [-0.7668,  0.5491, -0.3083],
        [-1.2309, -1.3998,  0.3947],
        [-0.5466, -0.3768, -0.6833],
        [ 0.3448,  1.6080, -1.1067]], requires_grad=True)

In [7]:
feature_1 = [0,3,4]
# feature_

## Tensor test

In [8]:
type(embedding_sum.weight)

torch.nn.parameter.Parameter

In [26]:
x = torch.Tensor([[1,1,1,1,1,1],[2,2,2,2,2,2],[3,3,3,3,3,3],[4,4,4,4,4,4],[5,5,5,5,5,5],[6,6,6,6,6,6]])
y = torch.Tensor([[1,1,1],[2,2,2],[3,3,3]])

In [27]:
x

tensor([[1., 1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6., 6.]])

In [28]:
y

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.]])

In [43]:
indices = torch.Tensor([[1,0,0],
                        [0,1,1],
                        [0,1,0],
                        [1,1,1]])
indices

tensor([[1., 0., 0.],
        [0., 1., 1.],
        [0., 1., 0.],
        [1., 1., 1.]])

In [45]:
indices.mm(y)

tensor([[1., 1., 1.],
        [5., 5., 5.],
        [2., 2., 2.],
        [6., 6., 6.]])

In [48]:
embedding_test = nn.EmbeddingBag.from_pretrained(embeddings=y, mode='sum')

In [50]:
embedding_test.weight

Parameter containing:
tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.]])

In [179]:
# List of indices to sum
list_of_indices = [[0],
                   [1,2],[],
                   [1],
                   [0,1,2],]

def gen_indices_n_offsets(list_of_indices):
    indices = []
    offsets = [0]
    last_offset = 0
    avg_val = []
    for l in list_of_indices:
        indices += l
        last_offset += len(l)
        if len(l) > 0: 
            avg_val.append(2)
        else:
            avg_val.append(1)
        offsets.append(last_offset)
    offsets.pop()
    return torch.LongTensor(indices), torch.LongTensor(offsets), torch.LongTensor(avg_val)

In [180]:
gen_indices_n_offsets(list_of_indices)

(tensor([0, 1, 2, 1, 0, 1, 2]),
 tensor([0, 1, 3, 3, 4]),
 tensor([2, 2, 1, 2, 2]))

In [181]:
indices, offsets, avg_val = gen_indices_n_offsets(list_of_indices)
embedding_test(indices, offsets)

tensor([[1., 1., 1.],
        [5., 5., 5.],
        [0., 0., 0.],
        [2., 2., 2.],
        [6., 6., 6.]])

In [182]:
def indices_generator(embeddings, n_resultant_embeddings=None, seed=7):
    random.seed(seed)
    p = len(embeddings)
    q = n_resultant_embeddings
    m = []
    for i in range(q):
        n = []
        for j in range(p):
            n.append(int(random.random()*2))
        m.append(n)
    return m

In [183]:
l = indices_generator(embedding_test.weight, 4, seed=5)
l

[[1, 1, 1], [1, 1, 1], [0, 0, 1], [1, 1, 0]]

In [184]:
def generate_list_of_indices(l_of_l):
    l = []
    for i in range(len(l_of_l)):
        indices = []
        for j in range(len(l_of_l[i])):
            if l_of_l[i][j] != 0:
                indices.append(j)
        l.append(indices)
    return l

In [185]:
lista = generate_list_of_indices(l)

In [186]:
lista

[[0, 1, 2], [0, 1, 2], [2], [0, 1]]