In [21]:
class PruebaFormat():
    
    def __init__(self):
        self.num_embeddings = 10
        self.embedding_dim = 10
        self.max_norm = None
        self.norm_type = 1
        self.scale_grad_by_freq = True
        self.mode = 'sum'
    
    @classmethod
    def hola(cls, nombre='mundo'):
        print('hola {}'.format(nombre))
        
    def extra_repr(self):
        s = '{num_embeddings}, {embedding_dim}'
        if self.max_norm is not None:
            s += ', max_norm={max_norm}'
        if self.norm_type != 2:
            s += ', norm_type={norm_type}'
        if self.scale_grad_by_freq is not False:
            s += ', scale_grad_by_freq={scale_grad_by_freq}'
        s += ', mode={mode}'
        return s.format(**self.__dict__)

In [22]:
PruebaFormat.hola()

hola mundo


In [23]:
x = PruebaFormat()

In [24]:
x.extra_repr()

'10, 10, norm_type=1, scale_grad_by_freq=True, mode=sum'

In [2]:
import numpy as np

x1 = np.arange(9.0).reshape((3, 3))
x2 = np.arange(3.0)

In [3]:
x1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [4]:
x2

array([0., 1., 2.])

In [5]:
np.multiply(x1,x2)

array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])